import { StyleSheet } from "react-native";
import { COLORS, FONT, SIZES, SHADOWS } from "../../constants";

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.white,
		paddingHorizontal: SIZES.medium,
	},
	logoContainer: {
		alignItems: "center",
		marginTop: 5,
	},
	logo: {
		width: "39%",
		height: 41,
		resizeMode: "contain",
	},
	datePickerContainer: {
		width: "100%",
		marginTop: 10,
	},
	datePickerRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "flex-start",
		paddingHorizontal: SIZES.small,
	},
	datePickerLabel: {
		marginLeft: 30,
		fontFamily: FONT.semiBold,
	},
	datePicker: {
		borderWidth: 1,
		borderColor: COLORS.white,
		borderRadius: 5,
		marginRight: 55,
		flexGrow: 1,
		height: 40,
	},
	datePickerText: {
		color: COLORS.primary,
		textDecorationLine: "underline",
	},
	productNameLabel: {
		fontFamily: FONT.semiBold,
		marginTop: SIZES.medium,
		marginLeft: SIZES.small,
		fontSize: 16,
		color: COLORS.darkGray,
	},
	searchContainer: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: SIZES.medium,
		marginTop: 10,
		backgroundColor: COLORS.white,
		borderRadius: 15,
		borderColor: COLORS.lightGray,
		borderWidth: 1,
		height: 50,
		marginBottom: SIZES.small,
		marginLeft: 10,
		marginRight: 10,
	},
	searchInput: {
		flex: 1,
		marginLeft: 40,
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
		height: "100%",
	},
	searchIconContainer: {
		position: "absolute",
		left: SIZES.medium + 10,
		zIndex: 10,
	},
	inputRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: SIZES.small,
		marginHorizontal: SIZES.small,
	},
	quantityInput: {
		flex: 1,
		backgroundColor: COLORS.white,
		borderRadius: 15,
		borderColor: COLORS.lightGray,
		borderWidth: 1,
		height: 50,
		paddingLeft: SIZES.medium,
		paddingRight: SIZES.medium,
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
	},
	unitInput: {
		flex: 1,
		backgroundColor: COLORS.white,
		borderRadius: 15,
		borderColor: COLORS.lightGray,
		borderWidth: 1,
		height: 50,
		paddingLeft: SIZES.medium,
		paddingRight: SIZES.medium,
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
		marginLeft: SIZES.small,
		justifyContent: "center",
	},
	pickerStyle: {
		paddingRight: SIZES.medium,
		fontSize: SIZES.medium,
		fontFamily: FONT.regular,
		color: COLORS.black,
	},
	separatorContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginTop: SIZES.large,
		marginBottom: SIZES.medium,
	},
	line: {
		height: 1,
		backgroundColor: COLORS.lightGray,
		flex: 1,
		marginLeft: SIZES.small,
		marginRight: SIZES.small,
	},
	separatorText: {
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
		color: COLORS.gray,
	},
	inputLabel: {
		fontSize: 16,
		fontFamily: FONT.semiBold,
		color: COLORS.darkGray,
	},
	inputLabelContainer: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 5,
	},
	inputLabelContainerRight: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "space-between",
		marginLeft: 10,
		marginBottom: 5,
	},
	nutritionInputRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: SIZES.small,
		marginHorizontal: SIZES.small,
	},
	nutritionLabelRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 3,
		marginHorizontal: SIZES.small,
	},
	nutritionInput: {
		flex: 1,
		backgroundColor: COLORS.white,
		borderRadius: 15,
		borderColor: COLORS.lightGray,
		borderWidth: 1,
		height: 50,
		paddingLeft: SIZES.medium,
		paddingRight: SIZES.medium,
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
	},
	nutritionInputRight: {
		flex: 1,
		backgroundColor: COLORS.white,
		borderRadius: 15,
		borderColor: COLORS.lightGray,
		borderWidth: 1,
		height: 50,
		marginLeft: 10,
		paddingLeft: SIZES.medium,
		paddingRight: SIZES.medium,
		fontFamily: FONT.regular,
		fontSize: SIZES.medium,
	},
	submitButton: {
		backgroundColor: COLORS.lightGray,
		borderRadius: 15,
		paddingHorizontal: SIZES.large,
		paddingVertical: SIZES.medium,
		alignItems: "center",
		justifyContent: "center",
		marginTop: SIZES.medium,
		marginBottom: SIZES.xxLarge,
		marginHorizontal: SIZES.small,
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		...SHADOWS.xLarge,
	},
	submitButtonText: {
		fontFamily: FONT.bold,
		fontSize: SIZES.medium,
		color: COLORS.white,
	},
	suggestionItem: {
		flexDirection: "row",
		alignItems: "center",
		padding: 10,
		borderBottomWidth: 1,
		borderBottomColor: COLORS.lightGray,
		backgroundColor: COLORS.white,
	},

	suggestionText: {
		marginLeft: 10,
		fontSize: 16,
		color: COLORS.darkGray,
	},

	suggestionsContainer: {
		backgroundColor: COLORS.white,
		borderRadius: 5,
		marginTop: 5,
		...SHADOWS.xxLarge,
	},

	spinnerContainer: {
		...StyleSheet.absoluteFillObject,
		justifyContent: "center",
		alignItems: "center",
		zIndex: 10,
	},
});

export default styles;
